### ISSUE TITLE
commits getting bugs?

### ISSUE THREAD

**Issue by Xxc233** [Xxc233/AutoCloverDown#1]
### There has a 'bug' of commit getting as the subcommit. Like this:
<img width="703" alt="2018-06-15 12 13 16" src="https://user-images.githubusercontent.com/40139892/41449752-8e3ada26-7095-11e8-8298-bf47e15ce4ba.png">

### Emmm,let's see what will happen to the next version's commits.

**Comment by Xxc233** [comment]
### Recently commit seem to be fine.Keep looking.

**Comment by Xc2333** [comment]
It's time to use xml format to get commit instead of using awk.
